#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "one"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto-completion-return-key-behavior = "complete"
auto-completion-tab-key-behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
name = "colorscheme"
[[layers]]
name = "operator"
[[layers]]
name = "fzf"
[[layers]]
name = "git"
[[layers]]
name = "test"

[[layers]]
name="lang#go"
[[layers]]
name="lang#dockerfile"
[[layers]]
name="lang#groovy"
[[layers]]
name="lang#java"
[[layers]]
name="lang#javascript"
[[layers]]
name="lang#json"
[[layers]]
name="lang#markdown"
[[layers]]
name="lang#lua"
[[layers]]
name="lang#php"
[[layers]]
name="lang#python"
[[layers]]
name="lang#ruby"
[[layers]]
name="lang#rust"
[[layers]]
name="lang#sh"
[[layers]]
name="lang#tcl"
[[layers]]
name="lang#toml"
[[layers]]
name="lang#typescript"
[[layers]]
name="lang#xml"

# Custom layers
[[layers]]
name="lang#bazel"
